// <auto-generated />
namespace WebApiSample01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class QuoteCreateAtAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuoteCreateAtAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202104201305295_QuoteCreateAtAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
